extends:
  - stylelint-prettier/recommended
  - stylelint-config-standard
  - stylelint-config-prettier

plugins:
  - stylelint-scss

rules:
  at-rule-no-unknown: null
  selector-pseudo-class-no-unknown: null
  scss/at-rule-no-unknown: true
