extends:
  - stylelint-prettier/recommended
  - stylelint-config-standard
  - stylelint-config-prettier

plugins:
  - stylelint-scss

rules:
  at-rule-no-unknown: null
  no-invalid-position-at-import-rule: null
  scss/at-rule-no-unknown: true
  selector-pseudo-class-no-unknown: null
