import {
  GetStaticPathsResult,
  GetStaticPropsContext,
  GetStaticPropsResult,
} from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Script from 'next/script';
import { resolve } from 'path';
import { ParsedUrlQuery } from 'querystring';
import { useEffect } from 'react';

import { App } from '@/components/App';
import { PROD } from '@/constants/env';
import { JupyterBookProvider, JupyterBookState } from '@/context/jupyterBook';
import { getHTMLFiles } from '@/utils/jupyterBook';
import { getPageData } from '@/utils/ssg';

interface Props {
  state: JupyterBookState;
}

/**
 * Build directory relative to the .next directory.
 */
const BUILD_DIR = resolve(__dirname, '../../../_build/html');

/**
 * Returns a list of paths to export during pre-rendering:
 * https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation
 */
export async function getStaticPaths(): Promise<GetStaticPathsResult> {
  const files = await getHTMLFiles();
  const routes = files.map((file) => file.replace(`${BUILD_DIR}/`, ''));
  const paths: GetStaticPathsResult['paths'] = [
    // Index page /.
    {
      params: {
        parts: [],
      },
    },
  ];

  for (const route of routes) {
    // Split route into URL parts.
    paths.push({
      params: {
        parts: route.split('/'),
      },
    });

    // Allow support for `/<path>` given `/<path>/index.html` in development
    // mode. Most web server support both `/<path>` and `/<path>/index.html`,
    // but Next.js needs to have it configured explicitly.
    if (!PROD && route.endsWith('/index.html')) {
      paths.push({
        params: {
          parts: route.replace('/index.html', '').split('/').filter(Boolean),
        },
      });
    }
  }

  return {
    paths,
    fallback: false,
  };
}

interface Params extends ParsedUrlQuery {
  parts?: string[];
}

/**
 * Extracts data from the Jupyter Book HTML files for pre-rendering at build time:
 * https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation.
 */
export async function getStaticProps({
  params,
}: GetStaticPropsContext<Params>): Promise<GetStaticPropsResult<Props>> {
  const files = await getHTMLFiles();
  const path = params?.parts?.join('/') ?? '';

  const [file] = files.filter((currentFile): boolean => {
    if (path) {
      return (
        currentFile.endsWith(path) ||
        currentFile.endsWith(`${path}.html`) ||
        currentFile.endsWith(`${path}/index.html`)
      );
    }

    // If path is undefined, then the current page is /.
    return currentFile.replace(BUILD_DIR, '') === '/index.html';
  });
  const state = await getPageData(file);

  return {
    props: {
      state,
    },
  };
}

/**
 * Component for rendering all pages for napari.org.
 */
export default function Page({ state }: Props) {
  const router = useRouter();
  const isSearch = router.asPath.includes('/search');

  // Remove non-JS fallback UI for search page.
  useEffect(() => {
    if (isSearch) {
      document.querySelector('#fallback')?.remove();
    }
  }, [isSearch]);

  return (
    <>
      <Head>
        <title>
          {state.pageTitle === 'napari' ? 'Home' : state.pageTitle} - napari
        </title>
      </Head>

      {/* Include static JS scripts required by search page. */}
      {isSearch && (
        <>
          {/*
            The `documentation_options.js` script fetches the documentation URL
            root from a DOM node with the id `documentation_options`. This is
            always set to `./` for the search page.
          */}
          <div id="documentation_options" data-url_root="./" />

          {/*
            Scripts that should load before interactive. This is mostly so that
            the scripts required by `searchtools.js` are ready before execution.
          */}
          {[
            'jquery.js',
            'underscore.js',
            'documentation_options.js',
            'doctools.js',
            'language_data.js',
          ]
            .map((src) => `/${src}`)
            .map((src) => (
              <Script strategy="beforeInteractive" key={src} src={src} />
            ))}

          {/*
            Scripts for running the Jupyter Book search engine. The
            `searchtools.js` script is for executing the search and the
            `searchindex.js` contains searhc index data generated by Jupyter
            Book.

            Search execution will begin immediately when the page loads if the
            search query parameter is provided.
          */}
          {['searchtools.js', 'searchindex.js']
            .map((src) => `/${src}`)
            .map((src) => (
              <Script key={src} src={src} />
            ))}
        </>
      )}

      <JupyterBookProvider {...state}>
        <App />
      </JupyterBookProvider>
    </>
  );
}
