# Workflow for running several tests for PRs to the main branch for napari.org
# theme frontend code.

name: Theme Tests

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'theme/src/**'

defaults:
  run:
    working-directory: theme/src/

jobs:
  # Runs several tests on the theme codebase to check for code style,
  # formatting, best practices, and run unit/integration tests.
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup Yarn cache
        uses: actions/cache@v2
        # use this to check for `cache-hit`:
        # (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies with yarn
        run: yarn install

      - name: ${{ matrix.name }}
        run: ${{ matrix.run }}

    # Run linters and tests as matrix strategies so that they:
    #   1. Show up as separate GitHub checks.
    #   2. So we can reuse the Node.js and Yarn installation steps
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: prettier
            run: yarn prettier

          - name: stylelint
            run: yarn lint:scss

          - name: eslint
            run: yarn lint:ts

          - name: tsc
            run: yarn type-check
